// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7szrC_301V1j_peCarFmTTSdChdzJs90',
    appId: '1:213974690236:web:baea0ad6a543033a54e3b9',
    messagingSenderId: '213974690236',
    projectId: 'messenger2-35c3b',
    authDomain: 'messenger2-35c3b.firebaseapp.com',
    storageBucket: 'messenger2-35c3b.appspot.com',
    measurementId: 'G-SSGPPZJGVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1QwVB4LC9wHpTsDgcFtUwNfia3EbM_8',
    appId: '1:213974690236:android:9a0beee0d521c75354e3b9',
    messagingSenderId: '213974690236',
    projectId: 'messenger2-35c3b',
    storageBucket: 'messenger2-35c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhKJLoPXoiTUhyZAcHKCxz3ebOOIX6Lg',
    appId: '1:213974690236:ios:4d7e4ba7f01f104954e3b9',
    messagingSenderId: '213974690236',
    projectId: 'messenger2-35c3b',
    storageBucket: 'messenger2-35c3b.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhKJLoPXoiTUhyZAcHKCxz3ebOOIX6Lg',
    appId: '1:213974690236:ios:4d7e4ba7f01f104954e3b9',
    messagingSenderId: '213974690236',
    projectId: 'messenger2-35c3b',
    storageBucket: 'messenger2-35c3b.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7szrC_301V1j_peCarFmTTSdChdzJs90',
    appId: '1:213974690236:web:7ee777bfa10caf3154e3b9',
    messagingSenderId: '213974690236',
    projectId: 'messenger2-35c3b',
    authDomain: 'messenger2-35c3b.firebaseapp.com',
    storageBucket: 'messenger2-35c3b.appspot.com',
    measurementId: 'G-TGJTYG373F',
  );
}
